### ISSUE TITLE
Enrich table component functionality

### ISSUE THREAD

**Issue by fateeand** [AbsaOSS/cps-shared-ui#117]
```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/129
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/135
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/148
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/131
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/151
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/133
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/136
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/153
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/144
```
