### ISSUE TITLE
Create API pages for components

### ISSUE THREAD

**Issue by fateeand** [AbsaOSS/cps-shared-ui#74]
```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/300
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/301
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/193
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/320
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/328
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/337
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/349
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/350
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/355
- [ ] https://github.com/AbsaOSS/cps-shared-ui/issues/362
```
